services:
  - type: web
    name: i-Mobilothon-backend
    env: python
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -k uvicorn.workers.UvicornWorker main:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11